# Site
name: 'Inglês para Brasileiros'
description: 'A sua fonte de informação para aprender inglês.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
url: 'https://inglesparabrasileiros.com.br'
baseurl: ''
disqus: 'inglesparabrasileiros.com.br'
email: 'andrepestana@gmail.com'
mailchimp-list: 'https://inglesparabrasileiros.us8.list-manage.com/subscribe/post?u=d45e3015a791bfb713151f683&amp;id=b974d510a2'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    andre-pestana:
      name:           Andre Pestana
      site:           https://andrepestana.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Olá, meu nome é André Pestana e sou desenvolvedor de sistemas, adoro tecnologia, psicologia, artes e aprendizado de línguas."
      email:          andrepestana@gmail.com
      twitter:        https://twitter.com/

    ivanilde-pestana:
      name:           Ivanilde Pestana
      site:           https://ivanilde.github.io
      avatar:         /assets/images/avatar2.jpg
      bio:            "Testadora de Software, adoro dançar, viajar e filmes que me emocionam."
      email:          ivanildel@gmail.com
      twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: andre-pestana
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]